apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentapp-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentapp-db
  template:
    metadata:
      labels:
        app: studentapp-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: studentapp-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: studentapp-db-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: studentapp-db-secret
                  key: database
