apiVersion: v1
kind: Secret
metadata:
  name: studentapp-db-secret
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.db.user }}
  password: {{ .Values.db.password }}
  database: {{ .Values.db.name }}
