#!/usr/bin/env bash
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; . "${HERE}/common.sh"
ENV_FILE="${REPO_ROOT}/.env.generated"

creds_usage(){ cat <<USAGE
Usage: scripts/cegm.sh creds <use|export|rotate> [args]

  use <profile> [region]     Set AWS_PROFILE/AWS_REGION in current shell and verify via STS
  export <profile> [region]  Write exported vars to ${ENV_FILE} (for new shells/CI)
  rotate <iam_user> [--yes]  Rotate IAM user access key: create+validate+write profile (+optional cleanup)
                             (dry-run unless --yes)
USAGE
}

creds_use(){
  local profile="${1:-aws-cli-client}" region="${2:-us-east-1}"
  export AWS_PROFILE="${profile}" AWS_REGION="${region}"
  info "Using profile=${AWS_PROFILE} region=${AWS_REGION}"
  aws sts get-caller-identity >/dev/null || { err "STS failed for profile=${AWS_PROFILE}"; exit 1; }
  info "Caller identity OK."
}

creds_export(){
  local profile="${1:-${AWS_PROFILE:-aws-cli-client}}" region="${2:-${AWS_REGION:-us-east-1}}"
  mkdir -p "$(dirname "${ENV_FILE}")"
  cat > "${ENV_FILE}" <<EOT
# Auto-generated by creds_export
export AWS_PROFILE=${profile}
export AWS_REGION=${region}
EOT
  info "Wrote ${ENV_FILE}. Source it with:  . ${ENV_FILE}"
}

creds_rotate(){
  local iam_user="${1:-}"; shift || true
  local confirm="${1:-}"
  if [[ -z "${iam_user}" ]]; then err "Usage: scripts/cegm.sh creds rotate <iam_user> [--yes]"; exit 2; fi
  local profile="${AWS_PROFILE:-aws-cli-client}" region="${AWS_REGION:-us-east-1}"

  info "Dry run: rotate access key for user=${iam_user} profile=${profile} region=${region}"
  if [[ "${confirm}" != "--yes" ]]; then
    warn "This is a dry run. Append --yes to perform rotation."
    return 0
  fi

  # Ensure we are not over the 2-key limit before creation
  mapfile -t keys < <(aws iam list-access-keys --user-name "${iam_user}" \
     --query 'AccessKeyMetadata[].{Id:AccessKeyId,Create:CreateDate}' --output json | jq -r 'sort_by(.Create)[].Id')
  if (( ${#keys[@]} >= 2 )); then
    oldest="${keys[0]}"; warn "At 2-key quota; deleting oldest ${oldest}"
    aws iam delete-access-key --user-name "${iam_user}" --access-key-id "${oldest}"
  fi

  info "Creating new access key..."
  create_json="$(aws iam create-access-key --user-name "${iam_user}")"
  new_id="$(printf '%s' "${create_json}" | jq -r '.AccessKey.AccessKeyId')"
  new_secret="$(printf '%s' "${create_json}" | jq -r '.AccessKey.SecretAccessKey')"
  info "New key: ${new_id}"

  # Update CLI profile (not shell env)
  aws configure set aws_access_key_id     "${new_id}"     --profile "${profile}"
  aws configure set aws_secret_access_key "${new_secret}" --profile "${profile}"
  info "Updated ~/.aws/credentials profile=${profile}"

  # Export persistent profile/region for shells/CI
  creds_export "${profile}" "${region}"

  # Validate with explicit creds to avoid cache issues
  info "Validating via STS..."
  AWS_ACCESS_KEY_ID="${new_id}" AWS_SECRET_ACCESS_KEY="${new_secret}" AWS_REGION="${region}" \
    aws sts get-caller-identity >/dev/null || { err "Validation failed for ${new_id}"; exit 1; }
  info "Validation OK."

  # Optional: deactivate any remaining older active key for this user (safer than leaving two actives forever)
  mapfile -t actives < <(aws iam list-access-keys --user-name "${iam_user}" \
    --query 'AccessKeyMetadata[?Status==`Active`].AccessKeyId' --output text | tr '\t' '\n')
  for k in "${actives[@]}"; do
    if [[ "${k}" != "${new_id}" ]]; then
      warn "Deactivating older active key ${k}"
      aws iam update-access-key --user-name "${iam_user}" --access-key-id "${k}" --status Inactive
    fi
  done

  info "Rotation complete. Profile=${profile} now points to ${new_id}"
}

case "${1:-}" in
  use) shift; creds_use "$@";;
  export) shift; creds_export "$@";;
  rotate) shift; creds_rotate "$@";;
  *) creds_usage; exit 2;;
esac
