apiVersion: v1
kind: Secret
metadata:
  name: studentapp-secrets
  labels:
    app.kubernetes.io/name: studentapp
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: studentapp
    meta.helm.sh/release-namespace: default
type: Opaque
stringData:
  jwt-base64-secret: {{ required "jwtSecret is required but not defined" .Values.jwtSecret | quote }}
