# ===================================================================
# Spring Boot configuration for the "dev" profile.
# ===================================================================

logging:
  level:
    ROOT: DEBUG
    tech.jhipster: DEBUG
    org.hibernate.SQL: DEBUG
    com.mabdullah.courseapp.gateway: DEBUG

management:
  zipkin:
    tracing:
      endpoint: http://consul:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: gatewayApp

  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false

  jackson:
    serialization:
      indent-output: true

  cloud:
    consul:
      enabled: true
      host: consul
      port: 8500
      config:
        enabled: true
        fail-fast: false
        format: yaml
        profile-separator: '-'
      discovery:
        enabled: true
        prefer-ip-address: true
        tags:
          - profile=dev
          - version='@project.version@'
          - git-version=${git.commit.id.describe:}
          - git-commit=${git.commit.id.abbrev:}
          - git-branch=${git.branch:}

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
    hikari:
      poolName: Hikari
      auto-commit: false

  r2dbc:
    url: r2dbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres

  liquibase:
    contexts: dev, faker

  messages:
    cache-duration: PT1S

  mail:
    host: consul
    port: 25
    username:
    password:

  thymeleaf:
    cache: false

  docker:
    compose:
      lifecycle-management: START_AND_STOP

server:
  port: 8080
  forward-headers-strategy: native

jhipster:
  gateway:
    rate-limiting:
      enabled: false
      limit: 100000
      duration-in-seconds: 3600

  cors:
    allowed-origins: 'http://consul:8100,https://consul:8100'
    allowed-origin-patterns: 'https://*.githubpreview.dev'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-gatewayApp-alert,X-gatewayApp-error,X-gatewayApp-params'
    allow-credentials: true
    max-age: 1800

  security:
    authentication:
      jwt:
        base64-secret: MTJhMjQ1ZmFlMjg3MjVmMzBmNTkyNTllZTMwNmFjYWQyZjgyNTZiNmEzMmE2ZmY3MzJhYzYwZGI2OWZiMjUxMjA4NTFjZGY5NDQzNTA2YWQ1ZmUxYWUzZmMyNjA5OGRkM2UyN2U0NjUyYzcxZWRkN2JlZjdhMjFjNWE3ZTgzZDY=
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000

  mail:
    base-url: http://consul:8080

  logging:
    use-json-format: false
    logstash:
      enabled: false
      host: consul
      port: 5000
      ring-buffer-size: 512
